# Generated by Django 5.0.6 on 2024-06-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(verbose_name='facebook')),
                ('instagram', models.URLField(verbose_name='instagram')),
                ('twitter', models.URLField(verbose_name='twitter')),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
            },
        ),
        migrations.AlterField(
            model_name='presentation',
            name='small_description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
    ]
