# Generated by Django 5.0.6 on 2024-06-23 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_blogcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'verbose_name': 'Comentario sobre la publicacion', 'verbose_name_plural': 'Comentarios sobre Publicaciones'},
        ),
    ]
