# Generated by Django 5.0.6 on 2024-06-23 22:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_blogcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'verbose_name': 'Comentario sobre el Blog', 'verbose_name_plural': 'Comentarios sobre el Blog'},
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='date_time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
            preserve_default=False,
        ),
    ]
