# Generated by Django 5.0.6 on 2024-07-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_alter_blogcomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='active',
            field=models.BooleanField(default=False, verbose_name='activo'),
        ),
    ]
