# Generated by Django 5.0.6 on 2024-06-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activar'),
        ),
    ]
