# Generated by Django 5.0.6 on 2024-06-23 22:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_publicationcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationcomment',
            name='date_time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
            preserve_default=False,
        ),
    ]
