# Generated by Django 5.0.6 on 2024-06-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_publicationcomment_date_time_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationcomment',
            options={'verbose_name': 'Comentario sobre la publicacion', 'verbose_name_plural': 'Comentarios sobre Publicaciones'},
        ),
    ]
