# Generated by Django 5.0.6 on 2024-06-24 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_alter_publicationcomment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publication.category', verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
