# Generated by Django 5.0.6 on 2024-07-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0007_publication_small_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='small_description',
            field=models.CharField(max_length=100, verbose_name='Pequeña descripcion'),
        ),
        migrations.AlterField(
            model_name='publicationcomment',
            name='comment',
            field=models.TextField(max_length=255, verbose_name='comentario'),
        ),
    ]
