# Generated by Django 5.0.6 on 2024-07-05 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0008_alter_publication_small_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationcomment',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_publication', to=settings.AUTH_USER_MODEL),
        ),
    ]
